server:
  app_name: "starter"
  app_prefork: true
  port: 8080
  host: "localhost"
db:
  name: "starter"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  timezone: "UTC"

auth:
  jwt:
    secret: agXi6CYABLOWuF73iFn7
    expiration: 604800 # 7 days
